### ISSUE TITLE
"No eres policia" Bice bug

### ISSUE THREAD

**Issue by Eduardox** [Armada-Azteca/ArmadaAztecaServer#100]
En los 5 sqms donde pasas (segundo piso del castillo) si das click al de enmedio dice "No eres policia"
No se por que no se sube la foto al git

**Comment by Eduardox** [comment]
![bice](https://cloud.githubusercontent.com/assets/1991318/8643341/2fef4a02-28f8-11e5-9bf8-bef43c809188.JPG)

**Comment by Eduardox** [comment]
Mas info de este pedo, cuando das use al item id 10756 te sale el mensaje de "No eres policia"

**Comment by armadaazteca** [comment]
Ya quedó. Gracias.
