### ISSUE TITLE
Kina aol solo sube sword

### ISSUE THREAD

**Issue by Eduardox** [Armada-Azteca/ArmadaAztecaServer#101]
Como ya se usa axe, el aol debería de subir esa skill también

**Comment by armadaazteca** [comment]
Ya quedó, solo hay que probarlo, en el test o en el normal mañana y luego ya lo cierro.

**Comment by YagValdes** [comment]
Me parece que al usar el cualquier aol de donacion y despues ponerte una wichi te regresan los skills al igual si primero pones la wichi y despues el aol, ya no agrega esa vida extra pero si los skills, se podria hacer que funcionen los 2 al mismo tiempo?
