### ISSUE TITLE
Agregar reglas en la pag donde creas tu account

### ISSUE THREAD

**Issue by Eduardox** [Armada-Azteca/ArmadaAztecaServer#104]
Se me ocurre que cuando creas el char salga un mensaje que diga 
"He leído y aceptado las reglas de Armada Azteca"
Y que no te deje crear el acc hasta que marques esa casilla, algo asi como lo de "Acepto los terminos y condiciones de uso" que viene en muchas paginas al registrarte o en programas para usarlos. Puede ser que las reglas salgan ahí en la misma pagina abajito o que el texto sea un vinculo a la pag. de reglas.
Esto lo digo por que hoy me tocó ver a un wey que le dijo a Isa "Esque no soy el dueño del char solo se lo subo de lvl" cuando le entregaba una donación (El vato no sabía que era ilegar sharear accs, ni que es motivo de delete) y me imagino que habrá gente que tampoco sabe algunas reglas. La mayoría no lee ese pedo de acepto los terminos, pero ps ya no tendrán excusas de "No sabía"

**Comment by armadaazteca** [comment]
No es donde se crea el char, pero si donde se crea la cuenta. Si lo voy a poner.

**Comment by YagValdes** [comment]
Si seria bueno aunque dudo que muchos aun asi lo lean :S porque incluso esta escrito cuando entras al char, salen 4 reglas y la numero 4 dice: No prestar accounts. Asi que de todos modos ahí estan advertidos

**Comment by armadaazteca** [comment]
Listo ya quedo, en la pagina ahora te pide que actives la casilla de que aceptas.
