### ISSUE TITLE
Error En Armor!

### ISSUE THREAD

**Issue by RessivaFretza** [Armada-Azteca/ArmadaAztecaServer#108]
e.e Pues para decir que las armor que dan en la quest de Super UH que protege death no sirve! No puedes ponertela en el slot! Y sobre una "duda" las armors de elementos la quest! Protegen mucho menos que la magma coat,terra coat y todas esas no deberían proteger un poco mas??

**Comment by RessivaFretza** [comment]
e.e  Pues para decir que las armor que dan en la quest de Super UH que protege death no sirve! No puedes ponertela en el slot! Y sobre una "duda" las armors de elementos la quest! Protegen mucho menos que la magma coat,terra coat y todas esas no deberían proteger un poco mas??

**Comment by armadaazteca** [comment]
SI se pueden poner, ocupas ser mago. Si deben proteger poco, porque vamos a sacar otras mas adelante.
