### ISSUE TITLE
Error en el Nombre del Mount! Magma

### ISSUE THREAD

**Issue by RessivaFretza** [Armada-Azteca/ArmadaAztecaServer#136]
Es un pequeño error, pero muchos no podran activarla por esto:
El nombre real: Perro Magma nombre de donacion y aparece como Perro Magama en el juego.
:PPP

**Comment by Aron154** [comment]
Ya bala lo sabe. xD

**Comment by RessivaFretza** [comment]
Jajajaja :v, ya me dijo :PPPP

**Comment by armadaazteca** [comment]
ya quedó este. Gracias!
