### ISSUE TITLE
Tp Webon lleva a Armonia y no a la ciudad de residencia

### ISSUE THREAD

**Issue by Eduardox** [Armada-Azteca/ArmadaAztecaServer#141]
Si mal no recuerdo el tp te llevaba a donde tuvieras residencia, y ahora te lleva a armonia. También pasa con las versiones roja/verde

**Comment by armadaazteca** [comment]
con god o con player? de donde es residente el char con el que probaste?

**Comment by GMROUSH** [comment]
Yo cheque eso, y si jala normal, te lleva a donde eres residente

**Comment by armadaazteca** [comment]
gracias roush, lo cierro y si ven algun otro pedo lo checamos.
