### ISSUE TITLE
Nerf a la wand de Mages

### ISSUE THREAD

**Issue by Aron154** [Armada-Azteca/ArmadaAztecaServer#147]
Bueno pongo esto por aqui para que no se le olvide a bala que hay que nerfearlos con un nerfeo a el modi y un poco a la wand ya que pega demasiado por nivel.... quedarian bien.

**Comment by armadaazteca** [comment]
Tenemos #158 para el modi. Que cambio proponen a la wand?

**Comment by armadaazteca** [comment]
Le puse que el daño se base mas en level y ml, a ver que tal.

**Comment by armadaazteca** [comment]
algun reporte de esto?

**Comment by Eduardox** [comment]
Varios me han dicho que sigue pegando mucho y se sigue curando mucho, que un kina 15k lo mata un 13k mage con modi

**Comment by armadaazteca** [comment]
le baje un poquito mas a la formula, solo al hit minimo, el random empezaba en 1/3 de la vida del char, ahora empieza en 1/4

**Comment by armadaazteca** [comment]
yo creo que estos valores ya estan bien, le hemos estado dando un poco mas de aguante a los priest y a los kinas, y haremos lo mismo con los pallys, asi que yo digo que el daño actual esta bien, como ven?

**Comment by Ponid** [comment]
Yep, esta bien, el que si abría que checar es el exevo vis max (o no recuerdo cual es, el que tienes de donación para magos) pega increíblemente fuerte en PvP y casi no tiene exaus.

**Comment by armadaazteca** [comment]
había un bug con la Sd's que no tenian exhaust no se si te refieras a ese, porque el de donacion hasta donde recuerdo es exactamente igual al vis mas de quest. solo el elemento cambia.

**Comment by armadaazteca** [comment]
Mientras, cerrare este issue entonces, y si aun esta el pedo de los combos de mago, lo checamos en otro issue. Me avisas aqui.
