### ISSUE TITLE
Posible error en sword de level 3k

### ISSUE THREAD

**Issue by Eduardox** [Armada-Azteca/ArmadaAztecaServer#150]
7:03 You see a Armada Azteca sword (Atk:400 physical + 70 ice, Def:80). It can only be wielded properly by warriors of level 900 or higher.
17:03 You see a Olympus sword (Atk:450 physical + 6 fire, Def:100). It can only be wielded properly by players of level 3000 or higher.

El arma de level 900 da +70 ice y la de 3k da +6 fire, me preguntó un player que si no debería de ser +60 de fire en el arma de 3k ya que si las usas vs alguien que no tenga huichi o botas la arma de level 900 pegaría mas duro

**Comment by RessivaFretza** [comment]
Me parece que no es un error @Eduardox los dias que andaban viendo cuanto pegaban su hit se elevaba muchisimo es por eso que Isa, lo dejo en +6 de fuego de hecho si lo pruebas si pega mas que la de lvl 900, aparte creo es mas rapida!

**Comment by armadaazteca** [comment]
correcto. En prubas pegaba mucho, mas fire. Pero acabo de ver que el script esta mal. Jala esta sword?

**Comment by Eduardox** [comment]
@armadaazteca A que te refieres con que si jala? Pega el daño normal + el fire y todo

**Comment by armadaazteca** [comment]
Si, pero parece que el error no afecto nada el ataque, asi que solo arregle el script y en mis pruebas no vi nada diferente. Ya quedo este show. Gracias!
