### ISSUE TITLE
Carcel del altiplano

### ISSUE THREAD

**Issue by armadaazteca** [Armada-Azteca/ArmadaAztecaServer#156]
Mapa de una carcel chingona, tiene que ser con celdas chicas, vamos a empezar con 20 celdas. Cualquier distribucion, las celdas pueden tener puerta, pero no de esas que se abren sin llave ni nada.

**Comment by Aron154** [comment]
Estoy aqui no ? :v:

**Comment by armadaazteca** [comment]
@Aron154 acepta la invitacion de github, este es para roush. Te doy otro si quieres.

**Comment by armadaazteca** [comment]
Excelente carcel @GMROUSH . Gracias.
