### ISSUE TITLE
exevo vis mas te mata en arena

### ISSUE THREAD

**Issue by armadaazteca** [Armada-Azteca/ArmadaAztecaServer#161]
Es cierto esto? Roush dice que tiene ya 2 reportes iguales.

**Comment by Ponid** [comment]
No vale mucho mi palabra, pero yes, yo vi los cuerpos personalmente en mini banderas.

**Comment by armadaazteca** [comment]
Si estabas ahí tu palabra vale más que la mía.  Algo más que nos ayude a replicar el bug? Pasa siempre? O solo a veces?

**Comment by Ponid** [comment]
Sinceramente los detalles de como paso apenas preguntarle directamente a "Lola Volcan", yo solo lo vi ocurrido.

**Comment by RessivaFretza** [comment]
Hola, pues yo lo que sabia del exevo vis mas, es del retraso, entonces cuando estas serca de la pz y te lanzan el exevo vis mas y te meten a pz por el retraso te llega a matar dentro de la pz y si te cuenta tambien como cuando te mataban y el vis mas llegaba hasta el depot

**Comment by armadaazteca** [comment]
Se modifico el spell para que cheque si esta en pz y de ser asi, no hace daño. A ver que tal.
