### ISSUE TITLE
Npc cambia wichis

### ISSUE THREAD

**Issue by armadaazteca** [Armada-Azteca/ArmadaAztecaServer#164]
Si hago un cambio en la wichi quiero aprovechar para cambiar el dibujo y id de las actuales para que no se encimen.  Un npc que te haga el cambio,  que se llame arregla wichi o algo así.

**Comment by RessivaFretza** [comment]
Bala no se si tengas planeado cambiarle algo a las wichis, no estaria bien que te subieran mejor un % de tu mana o vida tambien dependiendo tu vocación ya que 25mil a nivel mas de 12k ya no es nada?? (Creo ya lo habia mencionado una ves)
Por ejemplo:
Magos y Druids: 15%-20% De su Mana
Knights: 15%-20% de su Mana
Pallys: 10% Vida + 10% Mana
Algo asi para que sea servible a todo lvl, y aprovechando el NPC podría pedirte otros items o algunas misiones extras para cambiarlos por las nuevas Wichis! Asi primero necesitarian la primera wichi, mas otro esfuerzo pars conseguir una mejor wichi

**Comment by Eduardox** [comment]
Igual concuerdo que el NPC en lugar de "arreglarla" la mejore de alguna manera

**Comment by armadaazteca** [comment]
Pues ya se hizo este pedo, con la aguelita, cambio un poco la idea original, pero en si, ya quedo.
