### ISSUE TITLE
Nerf MAGE YA PORFAVOR !

### ISSUE THREAD

**Issue by Aron154** [Armada-Azteca/ArmadaAztecaServer#165]
Ya porfavor es urgente 2 semanas jugando Y ES IMPOSIBLE JUGAR CONTRA LOS MAGOS ME MATAN DE UN SOLO VIS MAS SOLO CON 1K DE DIFERENCIA DE NIVEL Y AGUANTAN DEMASIADO. 
Disculpen ser asi pero es que no se puede jugar es imposible es muy mala experiencia de juego jugar contra mages....
Se que no tienes tanto tiempo bala pero es urgente ya...

**Comment by armadaazteca** [comment]
We. Deja de poner posts inútiles aquí.  Ya te habías quejado y no te dije nada,  pero otra vez lo mismo y sin  aportar nada nuevo. Piensa antes de poner algo aquí, no es un foro. Ya hay algo y ya puse mi posición, lee bien y si no aportas algo espera y ya. No sólo a este pedo sino en general.
