### ISSUE TITLE
Bug - Broadcast

### ISSUE THREAD

**Issue by Ponid** [Armada-Azteca/ArmadaAztecaServer#167]
Simple BUG - Si intentas broadcastear con "." (punto) te quitan el dinero. No tiene mucha importancia pero bug al fin y al cabo.

**Comment by armadaazteca** [comment]
O sea, te refieres a que si pones: `!broadcast ". `

Te quita el dinero y solo se broadcastea el punto? Si es asi, no entiendo porque es bug, si no ps dime que comando es el que se usa.

**Comment by Ponid** [comment]
Nono, osea ya vez que no puedes mandar "." por broadcast, si pones `!broadcast "Asdasdasdas.` igual te quita el dinero.

**Comment by armadaazteca** [comment]
vientos, en el save ya debe quedar areglado esto. Gracias!
