### ISSUE TITLE
Error con puertas tapadas por puta wall (imagenes)

### ISSUE THREAD

**Issue by YagValdes** [Armada-Azteca/ArmadaAztecaServer#17]
Se crea un bug en las puertas y al poner una fusion fuera de la casa en este caso y que la "puta wall" quede tapando el paso
![1](https://cloud.githubusercontent.com/assets/9791622/5126902/443d8dc2-7096-11e4-8422-62bc170bbe37.png)

Cualquier persona entra a la casa 
![1 5](https://cloud.githubusercontent.com/assets/9791622/5127003/e87284b0-7096-11e4-87c9-f9408f24691d.png)

Y al momento de cerrar la puerta (solamente si las puertas estan arriba y a la izquierda del player) la puerta te vota hacia afuera de la casa, quedando en el mismo cuadro que la "puta wall"
![2](https://cloud.githubusercontent.com/assets/9791622/5127057/471094d0-7097-11e4-92e8-9485caf5f0db.png)

Al momento de moverte hacia cualquier lugar para no estar en la "puta wall", a todos los players en pantalla se les cerrara el juego :scream: 
![3](https://cloud.githubusercontent.com/assets/9791622/5127087/7e95d0fa-7097-11e4-9a31-3edc489f3534.png)

Notas: 
Este bug no sucede si es con cualquier otra wall, ya sea la wall normal, la armada prision o la terra wall, unicamente con la puta wall, con las otras unicamente al cerrar la puerta te saca de la casa y la wall se borra automaticamente

Solo se puede hacer si la puerta esta arriba o a la izquierda de player como antes se mencionó, porque si esta de lado derecho o abajo del player la puerta te vota hacia adentro de la casa

**Comment by armadaazteca** [comment]
esto ya esta arreglado y por cierto ya hay una nueva version del launcher que es mas rapido. por si lo quieres probar @YagValdes
