### ISSUE TITLE
Personajes de el Staff.

### ISSUE THREAD

**Issue by Aron154** [Armada-Azteca/ArmadaAztecaServer#173]
Bueno hago este Issue para que el staff ponga sus chares en los comentarios por lo siguiente que paso ayer con bala. que se hicieron pasar por mi.

- [ ] Que pongan todos los chares que usan en los comentarios con los que estaran Activos

- [ ] Y que haiga una contraseña que se pregunte cada vez que algun god quiera hablar con el staff por ejemplo no se Palomita algo asi solo lo hago para que no pase mas lo de que se hacen pasar por alguien mas.

**Comment by Lagunass** [comment]
Exageras un poco, no?

**Comment by Aron154** [comment]
Solo es una propuesta. :)

**Comment by armadaazteca** [comment]
yo digo que fue mas mi culpa we, no creo que sea necesario tanto pedo
