### ISSUE TITLE
Cambios en la información de player (pagina)

### ISSUE THREAD

**Issue by YagValdes** [Armada-Azteca/ArmadaAztecaServer#18]
Creo que estaría genial si en la pagina de armada cuando checas un player en lugar de salir un listado de 20 muertes sufridas por el player, porque no que solo salgan unas 10-15 muertes sufridas y tambien las ultimas 10-15 muertes hechas a alguien con el player que se esta checando (a quien mató).

Tambien poder checar los skills del player, seria mejor si por ejemplo:
si es kina, solo checar: lvl, ml, club, sword, axe, shielding, fishing
si es druid o sorcer, checar: lvl, ml, shielding y fishing
si es pally checar: lvl, ml, distance, shielding y fishing
o podrian checarse todos los skills, pero reduje a algunas porque no todos suben el mismo skill, por ejemplo un druid no creo que le importe mucho su skill de sword

Si se puede arreglar el apartado donde esta el top guilds que creo ya tiene muchas semanas sin ser reiniciado (el top tiene 872 frags).

Y por ultimo agregar en los broadcast los mensajes que dicen los gms o gods porque luego hay gente que no esta conectada y le avisan por mensaje o whatsapp que un gm o god dice algo por broadcast y no se entera porque no lo puede ver en la pagina.
PD no estoy 100% seguro si los broadcast de los gms y de los gods no aparecen tiene mucho que no veo que hablen por broadcast en armada.

- [x] Que se vean los tops en todos los skills y level en la pagina principal
- [x] Que cuando busques al player salgan listados sus skills ademas de las muertes
- [x] Que se muestren los players que han sido asesinados por este player

**Comment by armadaazteca** [comment]
Pues lo de las monedas azteca, va a esperar, luego hago otro issue con ese pedo, este post lo tomare como las mejoras para los skills y ese pedo. Hoy edite la pagina para que se vean el ranks de level, luego le voy a poner flechas para que cada que le den click a las flechas se vayan mostrando los tops de los demas skills y tambien modificare la pagina de info de players para que se muestren los skills del player al buscarlo

**Comment by armadaazteca** [comment]
Ya quedó
