### ISSUE TITLE
Buena carcel.

### ISSUE THREAD

**Issue by Aron154** [Armada-Azteca/ArmadaAztecaServer#180]
Muy bien hecha la nueva carcel me gustan los detalles de deterioro felicitaciones para el que la hiso. lo que si que no me gusto fue que esta muy estrecha pero quedo muy bien :) (Las felicitaciones es por si es un nuevo mapper)

**Comment by armadaazteca** [comment]
We entiende que no es foro. No abras issues a lo wey,  ya hay uno abierto para la cárcel,  usa ese para comentar.
