### ISSUE TITLE
Mini bug Wichi de priest

### ISSUE THREAD

**Issue by Aron154** [Armada-Azteca/ArmadaAztecaServer#181]
Bueno es un mini bug aqui chiquitito es que las wichis de priest se pueden stackear.

![wichi](https://cloud.githubusercontent.com/assets/17327983/13619703/a8696324-e558-11e5-909b-447a46f723b5.png)

**Comment by Eduardox** [comment]
Ya posteado en el #151 y la solución en el #164

**Comment by Aron154** [comment]
Yo digo que se pueden juntar las wichis no que te de doble vida y doble regeneracion.....

**Comment by Eduardox** [comment]
Igual en ese post dije lo mismo, que se juntaban y les confirmé que no hay pedo con la curación ni la regeneración o el armor ya que esas no se juntan.
Stackear = apilar/juntar/encimar/etc

**Comment by Aron154** [comment]
ya pues por cierto quiero tu opinion de una cosa que me mandaron a hacer me puedes mandar msg cuando entres ?
