### ISSUE TITLE
Jail a veces no kickea al player después del tiempo asignado

### ISSUE THREAD

**Issue by Eduardox** [Armada-Azteca/ArmadaAztecaServer#182]
Como les comenté a veces no los kickea
22:00 >>>GM Secreto Mordido<<<
 Extreme'paly ha sido encarcelado
Tiempo: 2 minutos.
Motivo: No se insulta a los GMs

Ese wey le dieron 2 minutos y ya lleva ahí como media hora

**Comment by armadaazteca** [comment]
Ya vi cual es el pedo, solo pasa con los chars que tienen la comita en el nombre ' voy a ver que onda pa arreglarlo, thanks

**Comment by armadaazteca** [comment]
Esto ya debe quedar arreglado en el siguente save. Gracias por reportarlo
