### ISSUE TITLE
SE TE MURIO EL SERVER QUEPEDO?

### ISSUE THREAD

**Issue by DaFuckinDraw** [Armada-Azteca/ArmadaAztecaServer#19]

**Comment by armadaazteca** [comment]
Porque? Ya confirmaste que hay pedos? de aqui no puedo conectarme pero ya le dije a isa.

**Comment by YagValdes** [comment]
Como que se murio el server? lo dices por que se reseteo un dia? o porque hubo una noche que lo cerraron por mantenimiento? o que sucedio? no entiendo

**Comment by armadaazteca** [comment]
Hoy no he hecho nada de eso, y el server esta vivo.

**Comment by DaFuckinDraw** [comment]
JAJAJAJAJA
ME REFERIA QUE YA NO HAY GENTE NO MAMES NI 50 SE CONECTAN WE QUEPEDO?

**Comment by DaFuckinDraw** [comment]
EL TITULO ERA PARA QUE TE LLAMARA LA ATENCION AJJAJAJAJAJA WEY YA NI 50 CABRONES SE CONECTAN OCUPAS HACER ALGO ALRESPECTO WE

**Comment by DaFuckinDraw** [comment]
NO HARAS UPDATE O ALGO WE ?

**Comment by DaFuckinDraw** [comment]
EL AÑO PASADO SE PUSO VERGA PORQUE HICISTE UPDATE Y SACASTE NEUVAS VIPS WE Y TODO EL PEDO 
saca nuevas vips o algo we aca chingon donaciones baratas we nose y promocionar el server we quepedo 
ya se te murio we el server we antes eramos hasta 300 weyes ahorita ni 50 we QUEPEDO SALVA ARMADA

**Comment by DaFuckinDraw** [comment]
NO TE CUESTA QUE LAS DONACIONES SEAN 2X1 O AMITAD DE PRECIO 
PARA QUE LAA GENTE SUBA Y DEMAS WE DEN GANAS DE DONAR WE Y DALO VARIO TIEMPO DALE A  LA GENTE TIEMPO DE JUNTAR LANA Y ASI TE DAS UN BREAK Y TE PONES A HACER UN UPDATE Y QUEST WE AL SERVER WE

**Comment by armadaazteca** [comment]
pues el server esta riviviendo, ya quitamos el lag y cuando haya alguna idea concreta de las donaciones hay que hacer un nuevo post aqui, mientras cerrare este.
