### ISSUE TITLE
BUG Bicentenario Traped.

### ISSUE THREAD

**Issue by Aron154** [Armada-Azteca/ArmadaAztecaServer#196]
Bue vengo a reportar este bug que si no tienes tp no tienes salida te quedas trapped para siempre amenos que bloqueen la quest a buscarte.... niciquiera tienes la opcion de morir. no se si sea un bug.

![bice](https://cloud.githubusercontent.com/assets/17327983/14022740/2dd00d6c-f1af-11e5-8280-8e55ff39d390.png)

**Comment by Eduardox** [comment]
Siempre ha sido así, sugieres agregar una manera de suicidarte ahí?

**Comment by Aron154** [comment]
ps si  mi personaje esta atascado ahi desde hace como 3 semanas.

**Comment by Eduardox** [comment]
Qué tal si te pones en una esquina, pierdes pz y entras a concurso
Que vaya el team con el que fuiste a que te rescate, así era antes :p

**Comment by armadaazteca** [comment]
una forma de suicidio no estaria mal

**Comment by armadaazteca** [comment]
Ya quedo un pk ahi XD
