### ISSUE TITLE
Reata siempre gana le lugar 2

### ISSUE THREAD

**Issue by armadaazteca** [Armada-Azteca/ArmadaAztecaServer#204]
Dicen que en rata el lugar dos tiene un numero muy elevado de wins.

**Comment by Ponid** [comment]
Y si, junto con el primero. Salen demasiadas runas.

**Comment by Eduardox** [comment]
Al momento de poner las runas, las de los primeros 3 lugares aparecen casi siempre sobre las runas de los otros lugares y no solo el segundo o el primero. 
Siempre he notado que en el primer lugar, es 100% seguro que aparecen unas 2 runas cuando se usa el comando por eso mismo nunca pongo mas runas porque se que el que esté en el primer lugar tendrá la ventaja de que aparecerá su runa 2 veces luego luego

**Comment by armadaazteca** [comment]
Siempre hay una runa que habrá mas hasta arriba, porque no hay forma de poner items abajo de otros items. Pero ya cambie el script para que esa runa final sea random, asi que ahora no siempre sera el lugar dos. Puede se cualquiera. Y aun asi, sobre esa ultima runa, puse otras 4 que no existen. Pero igual en lugares random, así que no es literalmente imposible, solo si habrá un lugar que tenga un poco mas de posibilidades de ganar.
