### ISSUE TITLE
Bug con la wichi

### ISSUE THREAD

**Issue by armadaazteca** [Armada-Azteca/ArmadaAztecaServer#21]
Al tener puesta la wichi, cuando se sube level o cuando se la ponen, la vida baja como a la mitad.

**Comment by Clitoriz** [comment]
No es que la vida baje si no que sube, pero eso les pasa  a los que son nivel menos de 3k

**Comment by armadaazteca** [comment]
Si ya entendi, es que da un chingo de vida, pense que daba menos vida. y siempre te deja el maximo de vida. Thanks @Clitoriz cerrare este pedo
