### ISSUE TITLE
Spam en Materápidas

### ISSUE THREAD

**Issue by Eduardox** [Armada-Azteca/ArmadaAztecaServer#212]
Algunos player (Maccare para ser mas especifico) se van al piso invisible del concurso Materapidas, desde donde puede hacer yell justo cuando jalan la palanca para que los concursantes no puedan ver la suma o resta que aparece sobre las cajas, haciendo que pierdan y/o gane algún camarada de el que lo tenga ignored.
Solución que propone Secreto Mordido: Quitar el piso invisible que hay sobre el concurso

**Comment by armadaazteca** [comment]
ya cerre esa parte
