### ISSUE TITLE
Balanceo druids 

### ISSUE THREAD

**Issue by armadaazteca** [Armada-Azteca/ArmadaAztecaServer#215]
Ocupamos algo muy rápido para druids.  No aguantan ni pegan tanto.  Me inclino por darles más aguante para empezar,  propongo que su Rod regrese un porcentaje del hit en mana al player. Que opinan,  el plan sería balancear para que lo que cura un mago en dos modis sea lo mismo que cure un druid en exactamente el mismo tiempo del cooldwn de esas dos modis, solo cuando el druid tentá el tope de ml ,  y que vaya bajando exponencial mente o más si no tiene tanto ml. Como ven?

**Comment by Ponid** [comment]
Me parece muy buena idea, siempre y cuando la formula de la Rod este muy bien hecha para que sea "técnicamente" la misma curación de los magos.

**Comment by Aron154** [comment]
Pa ke khieres saber eso jaja salu2

**Comment by EdzioAudutore** [comment]
Tengo druid 10.5k y con dos 1 boom que tire ya ando sin mana y pues si no
hay monsters o players al rededor para tirar deluxe es muy dificil curarte
mana antes de morir

**Comment by Aron154** [comment]
La unica manera de que el druid sirva es algun spell que le de protec all a todo el team porque que cure vida no tiene chiste el exura san te cura todo la uh como un 80% y los magos no tienen vida. osea para que sea support del team tiene que tener algun tipo spell que te de protec all

**Comment by Ponid** [comment]
Volveríamos a lo mismo @Aron154, gente subiendo druids nada más para usar ese spell, tal y como hacen para las paralyz.

**Comment by Aron154** [comment]
no creo porque el ed solo sera support no tendra tanto tanto daño... que si se pueda defender pero que tenga menos daño entiendes ?

**Comment by Ponid** [comment]
No. Si el druid no se puede curar NADIE lo usara, tan simple como eso @Aron154, entiendes?

**Comment by Aron154** [comment]
pues que sea necesario el druid que sea obligatorio que lo use un knight asi como en rl un knight sin un ED no sirve..... casi

**Comment by Ponid** [comment]
Ya, pero esto es Armada Azteca. No vale comparar Tibia RL con un OT.

**Comment by Eduardox** [comment]
Quizás el punto que quiere aclarar Aron es que haya una diferencia notable entre un mage y un druid. (Cosa que yo también creo y ya he comentado anteriormente si no me equivoco)
En tibia RL un sorcerer está enfocado a hacer daño mientras que un druid tiene un poco de enfoque en el soporte y no tanto en el daño. En RL tienes un sorcer para hacer el mayor daño posible en el menor tiempo, pero sin un druid gastan mas parar curar al Knight, no pueden poner wildgrowths, no pueden tirar waves de ice/terra, etc.
En otros juegos también, se tienen hechiceros y shamanes o cosas así, los dos son magos pero uno está enfocado a dar soporte como curar al equipo, subir la defensa, revivir, etc. y otro a mas que nada se enfoca en hacer daño.
Si los dos se curan, los dos hacen daño, los dos hacen lo mismo (aunque sea de distinta manera, pero hacen lo mismo) para qué tener dos magos? Total, si hacen lo mismo por qué no tener solo 1 mago?
No estoy diciendo que no me guste la idea de la rod que regenere % de mana, solo aclaro el punto de que hay que diferenciar a los dos magos de alguna manera:

- Puede ser que pues en si se curen y peguen igual, y la diferencia sean los elementos con los que pueden atacar mage(vis/fire/mort) priest(ice/earth).

- Que los mages se enfoquen en hacer daño como están actualmente, y los druid tengan un combate diferente pero no en tanto en hacer daño si no enfocado a cosas como por ejemplo "soporte" la rod que regenera mana, algun spell que reduzca defensa a cierto elemento del objetivo, alguna runa que reduzca el daño del objetivo, algun spell que aumente su defensa a cierto elemento en área. Quizás un mago si pega mucho y el druid no tanto, pero utilizando X spell ya le bajó el daño al mago (o cualquier otra voc/monster) y pegan igual, o con X spell se sube la defensa a cierto elemento y ya el mago (o cualquier otra voc/monster) no le pega tanto. (Claro, todo esto que no se stackee para que si 10 druids le tiran a 1 monster un spell que lo haga 10% debil a un elemento no se haga 100% debil y se quede como 10% o hasta un máx de 15% o algo)

Tocando el tema de los magos en Tibia RL, un sorcerer es mucho más fácil de usar que un druid. El sorcerer solo tira sus waves, aoes y ya. El druid tiene que cuidar su vida, cuidar la vida del team, poner wildgrowths donde se ocupen, etc. 
¿Por qué no hacer igual un mago más facil (solo tirar wand, mortal, vis mas y ya), y el otro un tanto más complicado de jugar pero que represente un mayor beneficio (tirar este spell, luego este, luego este, luego este, dependiendo de la sitaución)?

**Comment by armadaazteca** [comment]
No recuerdo si ya lo había comentado yo aquí,  pero el otro día le dije a isa que si los druids los hacíamos igual que mages y creamos otra vocacion que si sea 100% support. Pero ps si implicaría cambios algo drásticos. 

Definitivamente quiero mantener cierta diferencia por eso no les doy modi de saya y ya. Así que en eso tienes toda la razón,  prefiero innovar un poquito aunque no podamos hacerlos exactamente iguales. Tienen sus diferencias. Ayer ya hice las pruebas finales en 1vs 1 y se me hizo perfecto,  con buen bot,  quedaron 4-4 mago vs druid. Creo que vamos por buen camino.

**Comment by armadaazteca** [comment]
por lo pronto voy a cerrar este, y seguiremos viendo que cambios se harán a largo plazo.
