### ISSUE TITLE
Gallina Infectada Mount stackeadas se consumen todas al usarla

### ISSUE THREAD

**Issue by Eduardox** [Armada-Azteca/ArmadaAztecaServer#217]
Si tienes varias mounts stackeadas y le das use para ponertela, se consumen todas las que tenias en el stack en lugar de solo 1

**Comment by armadaazteca** [comment]
Como se consigue esa mount?

**Comment by armadaazteca** [comment]
Ya me acorde, como sea, en el save ya queda este pedo. Gracias.
