### ISSUE TITLE
Propuesta Newtype como premio en Concursos

### ISSUE THREAD

**Issue by Aron154** [Armada-Azteca/ArmadaAztecaServer#228]
Pues no se me parece una idea que si a el ganador de un concurso quiera un newtype pues el GM se lo pudiera dar como premio osea solo es una apariencia temporal hasta que desconecte el player que gane o muera.... no se si les interesaria.

**Comment by armadaazteca** [comment]
yo digo que esto mejor que sea en item para que sean permanentes.
