### ISSUE TITLE
Npc!

### ISSUE THREAD

**Issue by VyroNeoz** [Armada-Azteca/ArmadaAztecaServer#274]
hay un bug con el npc cazador de vampiros y el elegido en vez de hablar por el chat de npc lo manda por el default channel
como sugerencia cambiar el look del king, por el del rey tibianus y agregar un npc que haga las funciones del bank!!

**Comment by armadaazteca** [comment]
lo del bank no, porque aqui si se saca dinero a lo pendejo y ni se usa

**Comment by armadaazteca** [comment]
tons, las cuentas quedarian con limites enormes y pues alomejor se buguea

**Comment by armadaazteca** [comment]
lo del NPC king, sin pedos!
