### ISSUE TITLE
Errores en el mapa

### ISSUE THREAD

**Issue by VyroNeoz** [Armada-Azteca/ArmadaAztecaServer#285]
Abro aqui para subir los errores que me encuentro
![image](https://user-images.githubusercontent.com/60127859/77597872-ccb13680-6ec5-11ea-916b-7d4e9a1ea12e.png)
en el fracc calabaza me puedo meter a una house.
![image](https://user-images.githubusercontent.com/60127859/77597888-d89cf880-6ec5-11ea-90a0-78003f98dfff.png)
monster atrapado

**Comment by VyroNeoz** [comment]
![image](https://user-images.githubusercontent.com/60127859/84096924-c4e33780-a9c8-11ea-93be-1fabcb3130eb.png)
cuando uso esta escalera me deja a lado en vez de arriba

![image](https://user-images.githubusercontent.com/60127859/84096947-d2002680-a9c8-11ea-8948-cb4642ea899a.png)
cuando bajo la misma escalera me deja en la esquina derecha


![image](https://user-images.githubusercontent.com/60127859/84096977-e2b09c80-a9c8-11ea-8bac-1f4ec0cd9dd6.png)
y cuando subo esta, me deja aqui.

**Comment by armadaazteca** [comment]
mil anios despues, pero quedo
