### ISSUE TITLE
Bug Broad Channel

### ISSUE THREAD

**Issue by Eduardox** [Armada-Azteca/ArmadaAztecaServer#29]
Algunos broadcast no aparecen en el nuevo channel, no se que es lo que cause esto, pero al parecer los 10k+ no salen en el channel.
Deletion

**Comment by Eduardox** [comment]
Tampoco aparecen los broads de gods en el channel

**Comment by armadaazteca** [comment]
No se si sea conveniente dejar lo que sale en blanco, dejame pensarlo.

**Comment by armadaazteca** [comment]
tambien otro player reporto que los bans no salen.

**Comment by Eduardox** [comment]
el gritón tampoco sale

**Comment by armadaazteca** [comment]
Ya quedó
