### ISSUE TITLE
Concurso Carrera

### ISSUE THREAD

**Issue by VyroNeoz** [Armada-Azteca/ArmadaAztecaServer#300]
El dia de los concursos por motivo del dia del niño me percate, que en el concurso carrera, el primero que entra, es el que casi siempre gana, porque hay unos segundos en lo que se tardan en aparecer los player killer y asi toma ventaja, por eso sugiero bloquear la zp hasta que el gm cierre el concurso.

@armadaazteca

**Comment by armadaazteca** [comment]
Casi no he visto que lo hagan, pero si, el script limpia y se tarda un poco antes de poner los pks. riesgoso pero si se pueden aventar.

**Comment by armadaazteca** [comment]
si hicimos este cambio. A ver que tal queda. !
