### ISSUE TITLE
cambio en Broadcast

### ISSUE THREAD

**Issue by Butch-Walker** [Armada-Azteca/ArmadaAztecaServer#306]
cambiar los anuncios de GODS (blancos) al principal asi, aveces cuando estas subiendo lvl y ponen algún anuncio no alcanzas a ver por que se llena con los ataques que se les da a los mil monster que matas y se pierde

**Comment by VyroNeoz** [comment]
tambien los de las raid, a veces no se que salio por el spam del broadcast
pero tiene razon butch de repente cuando haces save no veo el msj
@armadaazteca

**Comment by armadaazteca** [comment]
que opinan del save automatico, lo que hice es que se mande en los dos lugares, tanto en blanco como en rojo y le puse signos, eso es suficiente para que se note? @VyroNeoz @Butch-Walker

**Comment by armadaazteca** [comment]
ps me aloque y me puse a codificar varios cambios inspirado en este issue. Cuando puedan chequen el post de discord donde explico los cambios y en el save lo checan a ver que tal quedo.

**Comment by Butch-Walker** [comment]
yo considero es suficiente, el problema era cuando estabas matando por tanto dato de hits a monster no se veía, pero si está colocado en los dos, está perfecto.
