### ISSUE TITLE
efectos de los sombreros

### ISSUE THREAD

**Issue by armadaazteca** [Armada-Azteca/ArmadaAztecaServer#307]
para saber que hace cada sombrero, estaria chido poder ver su efecto en wiki o algo

![image](https://user-images.githubusercontent.com/1322470/81975842-3e1b8480-95ed-11ea-9ca6-8d080909d354.png)

**Comment by armadaazteca** [comment]
@vyroNeoz crees que puedas ayudarme con esto? Te puedo conseguir los sombreros en el test, para sacar un mini gif y ponerlo en la wiki.

**Comment by armadaazteca** [comment]
segun yo no dan stats, jaja, y nomas es el efecto, pero si no , ps ni pedo, el chiste es que puedan ver que pedo en algun lugar.

**Comment by VyroNeoz** [comment]
Ya quedo esto, cerraras el issue o que mas quieres que agregue, ya sea con gif o demas?

**Comment by armadaazteca** [comment]
muchas gracias @VyroNeoz , aqui dejo el link para referencia:

http://armada-azteca.com/wiki/index.php?title=Helmets

quedo chingon!
