### ISSUE TITLE
Harvest - descripcion de items

### ISSUE THREAD

**Issue by armadaazteca** [Armada-Azteca/ArmadaAztecaServer#316]
QUe los items tengan name y digan que efecto tiene en el concurso.

**Comment by VyroNeoz** [comment]
![image](https://user-images.githubusercontent.com/60127859/84226002-3c3ac900-aaa6-11ea-8163-ce6869ecd2b2.png)
 podrias ponerme aqui que hace cada item?

**Comment by armadaazteca** [comment]
Es que ya teniamos esta imagen, solo que nunca la subimos:
![image](https://user-images.githubusercontent.com/1322470/84970460-5bf27280-b0e0-11ea-8932-801b6c09cf73.png)
