### ISSUE TITLE
Map - Issues

### ISSUE THREAD

**Issue by armadaazteca** [Armada-Azteca/ArmadaAztecaServer#319]
Caminos abajo de Tenoch que te dejan entrar al depot

Pozo en spingfield que te atrapa

**Comment by VyroNeoz** [comment]
jaja lo sabia, mi amigo y yo sospechabamos de ese bug en tenoch pero no sabiamos como, por cierto ya habia abierto un issue similar, este solo lo ocuparas para esos dos, porque encontre otros bug de mapa

**Comment by armadaazteca** [comment]
si ves alguno issue abierto puedes mencionar donde estan los bugs. Ahorita este lo cerrare, pero si ves ootro donde involucre algo en el map, ahi mismo ponlo, si nops crea uno nuevo y ahi mete los que tengas.
