### ISSUE TITLE
Modificar las reglas (de la pág. y las que aparecen al hacer log in)

### ISSUE THREAD

**Issue by Eduardox** [Armada-Azteca/ArmadaAztecaServer#34]
Creo que están algo desactualizadas y se contradicen las que aparecen en el juego y las de la pag, pues en armada dice que no uses bot (cuando debería de decir que no hay problema si estás supervisando el char), y entre otras que no se si sigan en pie (como la de vender cosas por cosas de tibia rl). Puede que confundan a players nuevos al ver que al hacer log in no se permiten ciertas cosas y en la pág dice que si.
Deletion.

**Comment by armadaazteca** [comment]
Se modifico el reglamento del login, y vere como acomodar la pagina

**Comment by armadaazteca** [comment]
ya quedo, en la pagina ahora el reglamento tiene su propio link cuando le das click en el titulo
