### ISSUE TITLE
Campas salen en el agua

### ISSUE THREAD

**Issue by armadaazteca** [Armada-Azteca/ArmadaAztecaServer#355]
Creo que nomas quitando que el agua de ese fracc sea walkeable, con eso se arreglaria

**Comment by IAmSnowball** [comment]
Podría ser, poner tierra también o poner las Campa en otras cuidades y no en una única Fracc.

**Comment by armadaazteca** [comment]
Por el momento. Para el pedo del agua parece que si funciono. Ya cambie el piso a no walkeable y no salio ninguna.
