### ISSUE TITLE
Reconsiderar el level de los items de bice

### ISSUE THREAD

**Issue by Eduardox** [Armada-Azteca/ArmadaAztecaServer#36]
Varios player me dijeron que reconsideraran el level que se ocupa para usar los items de bice, que porque están en donación y no deberia pedir tanto level. Yo opino que así está bien pero cuando donen por alguno se les aclare que ocupan 7k para usar los items.

**Comment by armadaazteca** [comment]
si, desde que hicimos el cambio, en la pagina pusimos que se pueden usar 7k o mas. Ya cheque en la pagina y si dice.
