### ISSUE TITLE
Ultimas 2 horas de stamina no se regeneran en 6 horas

### ISSUE THREAD

**Issue by Eduardox** [Armada-Azteca/ArmadaAztecaServer#39]
No se regeneran las 42 hrs al estar off 6hrs+, solo se regeneral hasta 40, tal vez ocurra porque las horas 40-42 corresponden a las happy hour que no funcionan igual porque dan 50%+ exp
Deletion

**Comment by armadaazteca** [comment]
Este bug ya lo habia visto, solo que no lo he arreglado, no puse lo de las happy hour. Simplemente no las acomode bien, voy a checar el fin a ver si ya queda.

**Comment by Eduardox** [comment]
Un player me dijo "no mames me estas quitando 2 horas de bot" hahaha pero yo digo que lo dijo jodiendo

**Comment by armadaazteca** [comment]
Ya lo puse solo hay que esperar al save para ver si funciona o probar en el test.

**Comment by Eduardox** [comment]
ya quedó

**Comment by armadaazteca** [comment]
thanks
