### ISSUE TITLE
Excluir a Gods y GM del contador online de la página

### ISSUE THREAD

**Issue by Eduardox** [Armada-Azteca/ArmadaAztecaServer#44]
Los god y gm aparecen en el Total de player online en la pág. Por ejemplo hay 2 mage 2 paladin 2 priest 2 warrior el total debería ser 6, si hay un god online sale 7 si hay 2 sale 8, ese contador no debería aplicar para gods o gms. Digo no afecta mucho pero ps aunque andes ghost sales ahí en ese pedo (Me han hablado players diciendo: ya te vi estas online dice la página)
Deletion

**Comment by armadaazteca** [comment]
ya lo actualizé
