### ISSUE TITLE
Corregir errores de link en la drescripción de Otservlist.org

### ISSUE THREAD

**Issue by Eduardox** [Armada-Azteca/ArmadaAztecaServer#47]
Estos links están mal en la descripción de la pág
https://dl.dropboxusercontent.com/u/2275<br />0855/launcher/Armada%20Azteca%20Launcher*****
http://armada-azteca.com/azteca/account/admin-accou<br />nt

Es obvio como debería de ser el link, pero puede que haya gente que no entre por no saber ponerlo bien

**Comment by armadaazteca** [comment]
Ya vi que esos espacios se ponen automaticos, pero lo acabo de editar, a ver en un rato que se actualize, si ya se ve bien, si no, buscare un acortador de URL.

**Comment by armadaazteca** [comment]
No jalo, asi que tuve que poner acordardores de URL, pero ya no se ve cortado al menos.
