### ISSUE TITLE
Riona no vende el pick

### ISSUE THREAD

**Issue by armadaazteca** [Armada-Azteca/ArmadaAztecaServer#51]
no lo he confirmado pero eso reportaron, tal vez me los chingue cuando hize las npcs con monedas de oro

**Comment by Eduardox** [comment]
Los pick los puedes comprar de a 1 y de a bp completa en el tianguis

**Comment by Eduardox** [comment]
Pero la riona si vende el pick

**Comment by armadaazteca** [comment]
seguro, yo lo probe y no me lo da.

**Comment by armadaazteca** [comment]
Ya quedo.
