### ISSUE TITLE
Bug con items que dan skill

### ISSUE THREAD

**Issue by Eduardox** [Armada-Azteca/ArmadaAztecaServer#55]
Algunos items (como las bow y las huichi) cancelan el bonus skill que dan otros.
Por ejemplo, me pongo mage aol (+20) slasky shield (+15) y luego me pongo huichi y me baja 20 de ml, o también las bow (cuando las bow deberian de dar +15) y te baja ml. No se muy bien que pedo, solo noté que se apendejan las bow y las huichi y cancelan el bonus skill que dan otros items

**Comment by armadaazteca** [comment]
Si, este es un bug perpetuo, creo que con la verson de engine que estamos usando no se puede hacer automaticamente, pero si debe haber forma de que en los scripts se modifique el valor, voy a revisarlo y si lo quiero arreglar, ya esta en mi lista.

**Comment by armadaazteca** [comment]
creo que ya arregle este pedo, el probma es que tengo que probar los items que causan este bug en el test antes de poder ponerlo en el server normal.

**Comment by armadaazteca** [comment]
Este bug me reportaron que sigue pasando con la wichi y el aol, segun el orden que te los pongas pierdes o ganas ciertos skills, tengo que revisarlo con mas calma, poque creo que ya tenemos forma de arreglarlo con esos cambios que hize al engine, lo checare!!

**Comment by Eduardox** [comment]
@armadaazteca 
Si te pones la huichi y luego el aol las skills no se afectan. Si te pones el aol y después la huichi las skills se cancelan. Esto pasa con las huichis de kina y paladin, pero no con las de druid o mage

**Comment by armadaazteca** [comment]
Oye @eduardox tienes el nombre de quien lo reportó?

**Comment by Eduardox** [comment]
@armadaazteca Me lo reportaron hace uff años (como 1 o 2) pero pues es algo que siempre noté, ahí le calé y vi que si te las pones en ese orden huichi > aol no pasa nada con las skills @armadaazteca

**Comment by armadaazteca** [comment]
ya quedó este bug milenario
