### ISSUE TITLE
Skills bajan al morir incluso cuando traes legs 

### ISSUE THREAD

**Issue by Eduardox** [Armada-Azteca/ArmadaAztecaServer#56]
No se si sea bug o no, pero me dijeron que no debería de bajarte skills si las traes al morir

**Comment by armadaazteca** [comment]
Asi es, las legs solo te protegen de bajar level y no vamos a hacer que bajes menos skill si mueres con ellas puestas. Tal vez en algun futuro hagamos algun otro item que ayude al skill, pero no las dos juntas.
