### ISSUE TITLE
Bug en Vip House #1166

### ISSUE THREAD

**Issue by Eduardox** [Armada-Azteca/ArmadaAztecaServer#58]
19:26 You see an open door.
It belongs to house 'Vip House 1166'. Edit uno owns this house.
ItemID: [5518].
Position: [X: 2408] [Y: 2210] [Z: 7].
En esta vip, hay 2 sqms que son parte de otra casa (sabrá de que casa sean haha), le puse un * a esos 2 sqm por mientras para que el dueño no tuviera pedos.
19:23 You see a red carpet.
ItemID: [4395].
Position: [X: 2415] [Y: 2239] [Z: 7].
19:23 You see a red carpet.
ItemID: [4398].
Position: [X: 2415] [Y: 2240] [Z: 7].

**Comment by armadaazteca** [comment]
Ya quedó. Gracias!!
