### ISSUE TITLE
Pequeño error en letrero de pocion de exana vis

### ISSUE THREAD

**Issue by Eduardox** [Armada-Azteca/ArmadaAztecaServer#60]
Al final de el precio aparece un efecto que corresponde a la terra trap, no se nota a menos de que leas el server log
11:18 You see a sign.
You read: Nombre: Poscion para aprender exana vis
Precio: 
4 cacas de pechan
4 huevos de gallinita
100 fichas de casino
100 bear paw
100 cascabeles de anaconda
100 ojos infectados

Efecto: La pones y es invisible, cuando la pisan se atrapa el player que la pisÃ³.

ItemID: [1429].
Position: [X: 173] [Y: 58] [Z: 6].

**Comment by armadaazteca** [comment]
Ya quedó.
