### ISSUE TITLE
Cambios Zona de Demons

### ISSUE THREAD

**Issue by Eduardox** [Armada-Azteca/ArmadaAztecaServer#65]
01:51 You see dirt.
ItemID: [351].
Position: [X: 482] [Y: 1242] [Z: 7].
01:51 You see dirt.
ItemID: [354].
Position: [X: 476] [Y: 1246] [Z: 7].
Hay que borrar las cadenas que estan por ahi
Y también hay que poner pz en la casa del centro que ahi es donde llegan los chars
Estas escaleras no jalan
02:00 You see a ramp.
ItemID: [1393].
Position: [X: 416] [Y: 1241] [Z: 7].

**Comment by armadaazteca** [comment]
ya quedo
