### ISSUE TITLE
Duelo de hombres prohibir entrada a chars -1k a la palanca

### ISSUE THREAD

**Issue by Eduardox** [Armada-Azteca/ArmadaAztecaServer#69]
A veces se quedan parados chars -1k donde se ponen para la palanca, estaria bien cambiar el pilar donde das click para que te mande a la palanca para que solo entren 1k+
Position: [X: 571] [Y: 258] [Z: 7].Position: [X: 573] [Y: 258] [Z: 7].

**Comment by armadaazteca** [comment]
Lo voy a poner a 1k, pero porque 1k??

**Comment by Eduardox** [comment]
Pues que va a hacer un -1k ahi, si no puede pvp
