### ISSUE TITLE
LVL para noobs

### ISSUE THREAD

**Issue by DaFuckinDraw** [Armada-Azteca/ArmadaAztecaServer#7]
Bueno aqui publicare pensando para los noobs, 
yo opino que ya tienes un server lo bastante peludo que ya el mas alto va en 66k entonces, pues ocupas que los noobs tengan acceso a mas formas de lvl porque contemos las zonas para subir lvl,
Ahora esto es pensando en que ya son mm aproximadamente 5k porque llegar a ese nivel es sencillo osea tampoco se los pones tan facil.

1.- Arkania (respawn de pedos de bala) .- este es bastante amplio pero no tan eficaz porque es una recta entonces el subir y limpiar todo al regresar no obtienes suficientes pedos y es lento el que se respawnie ahi ahora yo digo que hasta eso estabien, pero para 1 persona el que esten 2 ya se chingaron, o 3 ahora pues si quieres gente que suba que obtenga cosas y que asi le den ganas de donar pues debes de ser un poco flexible para que puedan probar lo que es armada siendo ya un poco alto 
2.-Smurfs (4 respawn de goblins) estos respawns estan bien si, vas a usar los 4, he subido char ahi en 2 respawn y es muy lento no se que tanta paciencia tenga yo.
Pero si estaría bien una zona en la que debas ser 10kmas y pegues el 20k y ya no tengas acceso ahora creaste 20kmenos, pero pues no mames eso es comodidad para el que tiene chars chingones, con set, osea no llega asi un noobsito con morgana, medusa.. o lo basico basico.
si estaria bien una zona ahi de 10kmas alomejor puedes poner que junten algo para accesar y tengan acceso unicamente el char con el que juntaron las cosas eso lo pone interesante y no una cosa del otro mundo.. ( y ya piensas en 20kmenos en que solo estaran los que saben quepedo tienen sets y todo osea no le quitas lo interesante a 20kmenos porque solo llegaran unos pocos que quieran subir comodamente, rapido y eficaz, y en la zona nueva que se haga el desmadre que tenga que hacer ahi estaran bastantes noobs y todo entonces pues sera divertido como se dan en la madre, AHORA esa zona no la puedes hacer ni muy grande ni muy chica pero tienes que considerar que no va a lvl 1 por 1 entonces pues hazla 1 isla y media de goblins aprox para que se arme el desmadre ahi con chingo de noobsitos, OJO si ponle mm restriccion de acceso que junten algo para poder entrar y no se que tan complicado sea puedes ponerle que de acceso mmm 5 dias y demas asi estaran juntando y no se las dejas tan facil pero no imposible.

Asi habria mas gente porque esta es mi razon por la cual pienso para los noobsitos

Si te das cuenta, hay un chingo de noobs de lvl 1k a 10k, 12k , 13k, 14k y ahi se quedan porque ya no hay una zona que rinda para subir considerablemente rapido, ya no hay entonces que es lo que provocas, que se retiren, no le hayan el chiste, de subir porque no conocen bien, y finalmente se retiran se salen de armada y ya armada pierde publico, entonces debes de pensar en todo eso, armada esta pensado para QUIERES LVL? DONA VIPS y pues namas los de mexico pueden donar. 
entonces no le quitas lo interesante a las vips pero pues si haces que se retiren muchos porque no pudieron subir nunca que porque no tienen ni items ni donde poder subir.

NOTA: creo esa zona sirviria mucho porque asi los noobs van a querer ser 10k para poder entrar, a lvl y asi subir, y es mas puedes hacerla que entren desde 12k para que se la pelen tantillo. 
ZONAS NUEVAS PARA NOOBS 10KMAS,

**Comment by armadaazteca** [comment]
Ya hicimos mas zonas pa nobs. y vamos a poner un npc que de la info
