### ISSUE TITLE
Queja Slasky Spells Quest

### ISSUE THREAD

**Issue by Inconforme** [Armada-Azteca/ArmadaAztecaServer#75]
Vengo yo en nombre de todo New Revolution no a mentarte la madre porque esas te llueven diario, pero si a decirte que te mamaste con la quest. Primero se enojó Isa porque según la hicimos muy fácil porque la vimos en el test. En primera nosotros no abrimos el test, ustedes lo tenían abierto. En segunda no la pudimos hacer en el test, la primera vez que la intentamos pensamos que la habías cerrado para no poder pasar y ya después volvimos a intentar y nada mas nos baitearon con animaciones el día que entró a las 6am Isa a bannear. Tuvimos que entrar 2 veces a hacerla en el armada normal y le dimos como 4 vueltas a todo el camino para poder encontrar la entrada. Tanto que se enojaron que la hicimos fácil y todavía se la ponen mas fácil a los Azteca Porno. ¿Qué privilegios gozan ellos? Tienen algún retraso mental? Padecen de sus facultades mentales o algo por el estilo? Nosotros la hicimos como estaba originalmente, también nos lureaban y no nos dejaban hacerla. Y llegas a ponerles todo super fácil para que la hagan ellos. En la pagina de armada  dice que todo es parejo para todos, ahí no se vio en lo mas mínimo. Ellos traen mas nivel que todos nosotros y ni así la podían hacer. También les vas a poner mas fácil bice para que la puedan hacer? Porque tampoco han podido con esa.

El ot es verga, no vale la pena que lo mates por pendejadas como esa.

Atte:
Todo New Revolution

Pd: Se hace el intento de hablarte de manera educada, a ver si así nos pelas

**Comment by armadaazteca** [comment]
Primero que nada, este no es el medio para este tipo de comentario/feedback/reclamo, pero como quiera, me tomare el tiempo para contestarte aquí solo esta vez. Antes que nada, aclaro que este proyecto de github es para darle seguimiento a todo lo que tiene que ver con el código de armada, el mapa y otras ideas para el server, en armada estoy disponible prácticamente diario a varias horas, ademas de el whats y el face, pero bueno eso aclarado pasamos a responder tu queja. 

 Así como tu citas la página, yo también la voy a citar. En su momento hice la aclaración de que hacer un server lleva mucho tiempo y esfuerzo, además se le suma un componente que es muy importante en este tipo de juegos que es "la fase de pruebas", somos solamente dos personas haciendo la parte mas dificil de armada, que son el mapeo y los scripts, cuando nosotros hacemos algo es muy dificl probar todos y cada uno de los aspectos, podriamos llevarnos meses de pruebas porque solo somos dos personas, pero eso la verdad no es muy práctico, asi que lo que decidimos hacer es: 
 - Terminar la quest, comando, spell o item y probarlo un poco en el test.
 - Pedir ayuda a algunos players, que muy amablemente nos ayudan a entrar al test y darnos comentarios.
 - Una vez que están terminados los cambios o confirmado todo, ponerlo en el server.
 - Si, por algun motivo, se encuentra algo que no habiamos contemplado en la idea original, lo vamos a cambiar. 

Este último punto es la clave aquí y es lo que mencione hace tiempo en la pagina a raíz del reset, Los cambios van a tener que ser graduales y no sera como antes, que si hice algo y no funciona o no lo usan como yo lo planeaba, lo dejaba y ya ni modo, entiendo que esto puede causar algunas veces que los items o quest cambien para algunos, pero eso es lo que acorde junto con Isa que va a pasar en el nuevo Armada (Mucho de esto tomado de mi experiencia con LOL y la manero que Riot Games hace las cosas). La finalidad es simple: quiero un server a mi gusto, si yo hice algo que no esta dando el resultado que esperaba lo voy a cambiar, y el periodo de pruebas no debe ser exageradamente largo. Asi que lo que paso con esta quest, seguramente pasara con otras. Las cosas que no me gustaron de lo que pasaba en esta quest:

- Los players lureaban y llenaban de monster sin arriesgar nada (char nobs pisaban la zona esa)
- Los players al final del camino de la serpiente les tapaban el paso

Esas cosas no me gustaban, y las fui arreglando, aun ahorita, no le veo sentido a la forma en que los players bloquean el camino para que los demás no hagan la quest, porque no lo están haciendo con skill, solo pisar y ya, dejar a los monsters bloquear el paso.
