### ISSUE TITLE
Mandar chars a armonia cuando los desinvitan de una casa

### ISSUE THREAD

**Issue by Eduardox** [Armada-Azteca/ArmadaAztecaServer#77]
El problema de los reds sigue aún, me ha tocado ver como hacen a 2 vatos red de la misma manera. Los llevan a una vip donde tienen 7 chars (ya sea mc o siendo personas diferentes, casi siempre mc) hasta el fondo con poca vida, le dicen a la victima que tire un spell o una runa, después desinvitan rápido a los 7 chars y los saca de la vip, haciendo que el spell que tiraron los mate y se haga red al instante. Luego lo matan y pues se quedan con sus items.
Esto no es bug, pero no veo justo que se aprovechen así de los noobsillos (varios de los que les han hecho esto son gente que ha donado). Y lo peor es que es el mismo vato el que hace esto, siempre el mismo wey

**Comment by Eduardox** [comment]
O como solo lo hace 1 wey, otra podría ser tenerlo checado para banearlo de mc cuando lo intente denuevo

**Comment by RessivaFretza** [comment]
Yo digo que la primera opcion es muy buena ya que si surgen mas de estos tipos no podras checar a todos y con la primera arreglas el problema desde la raiz!

**Comment by armadaazteca** [comment]
ya tengo esto en el test, solo que no todas las casas "pertenecen" a una ciudad, solo tengo que terminar eso en el mapa y ya lo pondre en el server. El fin sin falta queda.

**Comment by Eduardox** [comment]
Ya quedó

**Comment by armadaazteca** [comment]
Ya quedo este pedo, en el save el fracc que faltaba ya tiene templo en armonia. Y lo del 10 tambien ya quedo.
