### ISSUE TITLE
Hacer stackeables algunos items

### ISSUE THREAD

**Issue by Eduardox** [Armada-Azteca/ArmadaAztecaServer#82]
Deberíamos hacer stackeables items como mother soil, patas de xerxes, condones de hulk, vampiric crest, etc. Cuando vas a lotear cosas es un castre acomodar todo en bps.
Podría ser que también los cigarros y legs

**Comment by armadaazteca** [comment]
Algunos si los queremos asi sin stackear como las legs, pero otras cosas si las podemos hacer stackeables, tengo que cambiar el cliente y los scripts de ser necesario por si se usan o algo asi. Lo checare con esa, que es la que esta actualizando el cliente ahorita.

**Comment by armadaazteca** [comment]
Los que si vamos a hacer stackeables (Marcados los que ya probé en el test):
- [x] mother soil
- [ ] patas de xerxes
- [ ] condones de hulk
- [x] vampiric crest
