### ISSUE TITLE
Al morir se te regenera completamente la stamina

### ISSUE THREAD

**Issue by Eduardox** [Armada-Azteca/ArmadaAztecaServer#83]
Cuando mueres se te regenera mucho la stamina, tengas 10 20 30 horas se te sube a 41-42

**Comment by armadaazteca** [comment]
En la prueba, se regenero a 42:00 con solo 10 minutos de log-off, estando en 1000, quedo en:

Antes:
```
+--------+-------------+-------+---------+------------+------------+
| id     | name        | level | stamina | lastlogin  | lastlogout |
+--------+-------------+-------+---------+------------+------------+
| 188345 | Soy un Mago | 10000 |    1000 | 1436253761 | 1436253784 |
+--------+-------------+-------+---------+------------+------------+
```
Despues:

```
+--------+-------------+-------+---------+------------+------------+
| id     | name        | level | stamina | lastlogin  | lastlogout |
+--------+-------------+-------+---------+------------+------------+
| 188345 | Soy un Mago | 10000 |    2520 | 1436254458 | 1436254644 |
+--------+-------------+-------+---------+------------+------------+
```

**Comment by armadaazteca** [comment]
Hize unos cambios, cuando tengan chance lo calas @Eduardox porfa y me avisas.

**Comment by Eduardox** [comment]
Char con 34:25 de stamina, me descoencté a las 7:05 pm. Lo voy a logear unos 15 min a ver hasta donde sube

**Comment by Eduardox** [comment]
Morí y la stamina sigue igual, 34:25

**Comment by armadaazteca** [comment]
Es que la stamina empieza a regenerarse despues de estar desconectado al menos 1 hora, y si te desconectas 4 horas, te la regenera toda. Esa era el plan original.

**Comment by Eduardox** [comment]
Deja calar entonces

**Comment by Eduardox** [comment]
8:40 PM: Stamina 34:25
10:45 PM: Stamina 34:40

**Comment by Eduardox** [comment]
Al parecer si se regeneró toda en 4 horas

**Comment by armadaazteca** [comment]
Entonces ya funciona como originalmente debio funcionar, se quejaran pero asi es. ni pedo. Gracias @Eduardox por probar
