### ISSUE TITLE
La fusion da debug al pisarla

### ISSUE THREAD

**Issue by armadaazteca** [Armada-Azteca/ArmadaAztecaServer#88]
Al pisar la fusion y moverse da debug, ya lo habia arreglado pero no me acuerdo como.

**Comment by YagValdes** [comment]
Es el mismo bug del #17 ? :S

**Comment by armadaazteca** [comment]
si, pero en un update, me planche los cambios en el item y otra vez pasaba. Ya esta arreglado pero solo en el test.
