### ISSUE TITLE
Problemas con concurso bola

### ISSUE THREAD

**Issue by Eduardox** [Armada-Azteca/ArmadaAztecaServer#89]
Ultimamente entre los gms y yo hemos notado que hay problemas con el concurso, no sabemos que lo causa pero esto es lo que ocurre a veces (la mayoría de las veces no hay pedos)
- La bola sale 2 veces
- Las piramides no se regeneran
- La bola a veces no aparece

Ya le pregunté a schuterz y ressiva que si estan seguros de que si borran la bola, y los 2 dicen que si la borran. Así que probablemente este bugeado o se bugee a veces

**Comment by RessivaFretza** [comment]
Si! Antier que estabamos Schuterz y yo, este Schuterz activo bola. Ibamos llegando los 2 y no aparecio la Bola y en la siguiente partida estaba la bola 2 vaces, talves cuando no aparece coincide con las veces que aperecen las 2 bolas. Talves no se este activando bien, yo creo!

**Comment by armadaazteca** [comment]
Las piramides, estan seguros que no solo es con la de las esquinas?? tal vez si un player esta arriba o si se activa dos veces, puede que si salga doble. SI pueden hacer pruebas y decirme que es, estaria chido, de todos modos el fin tratare de hacer pruebas, pero tal vez hasta el que sigue.- 18/7

**Comment by armadaazteca** [comment]
no he visto que onda con esto, no han detectado cuando es que pasa? alguna otra pista o algo?

**Comment by RessivaFretza** [comment]
Por lo que sucedía cuando yo estaba es que si en 1 partida no aparecía la bola, en la siguiente partida aparecían 2 veces! Lo de las piramides nunca me paso a mi! Pero en una ocacion como ya lo dije antes con Schuterz no aparecio 1 ves y luego aparecio 2 veces y asi varias veces!

**Comment by Eduardox** [comment]
Pues al parecer a alguien se le olvidaba borrar la bola (aunque todos dijeron que no), ultimamente no ha pasado nada de esto

**Comment by armadaazteca** [comment]
Ya quedo, asi es como quedara despues del save:

 - Se activa el concurso igual que antes
 - El gm se tiene que poner justo donde salia la bola antes, que es, frente a la piramde 4 de izquierda a derecha
- El gm dice el comando: !bola y ya, la bola aparece bajo el, y las piramiditas se borran todas juntas.

cualquier cosa me avisan y lo re-abro.
