### ISSUE TITLE
Players reprtan que ya no pueden entrar a armada usando ipchanger

### ISSUE THREAD

**Issue by Eduardox** [Armada-Azteca/ArmadaAztecaServer#96]
No se que pedo, me dijeron que antes si se podía y que como en la tarde ya no han podido entrar con el ip changer

**Comment by armadaazteca** [comment]
que ip usan? que te pasen el dato,

**Comment by Eduardox** [comment]
armadaazteca.servegame.com

**Comment by armadaazteca** [comment]
si, creo que ya se arreglo, gracias
