### ISSUE TITLE
comando para crear las apuestas del casino

### ISSUE THREAD

**Issue by armadaazteca** [Armada-Azteca/ArmadaAztecaServer#97]
actualmente el comando es:
```
!agregarapuesta "1, TSM, DIGNITAS, 11/07/2015, 19:30
```

Hay que agregar dos opciones mas, una para el **tipo de evento** y otra para activar o no la opcion de **empate**, por ejemplo:
```
!agregarapuesta "1, esport, noempate, TSM, DIGNITAS, 11/07/2015, 19:30
!agregarapuesta "1, americano, empate, Steelers, Jaguars, 11/08/2015, 10:30
!agregarapuesta "3, UFC, noempate, Mendes, McGregor, 11/08/2015, 10:30
```

**Comment by RessivaFretza** [comment]
Esto lo pueden hacer lo puede hacer cualquiera? Si quieren con gusto puedo apuntar a dar de alta: UFC, Futbol Local, Americano, y otro de futbol

**Comment by armadaazteca** [comment]
Si el que sea, solo que si necesitamos que lo actualize de verdad, y con cuidado con los tiempos, que de verdad seas fan para que no tengas que andar preguntando o poniendo informacion erronea, ya que tenga los comandos, pedire ayuda a ver quienes se apuntan. Quiero tambien cambiar la forma de ganar/perder. Ya que tenga todo eso les aviso. 

Thanks

**Comment by RessivaFretza** [comment]
Pues de Americano podria asegurarme yo! Vale vale tu me avisas!

**Comment by Eduardox** [comment]
El Schuterz me dijo que se podía encargar de los Lolsports

**Comment by armadaazteca** [comment]
si de echo platicando con el salio lo de los cambios que hay que hacer en el comando porque en esports no aplica lo de empate. Y como puede haber nombres parecidos también salio que hay que especificar el tipo.

**Comment by armadaazteca** [comment]
ya quedo este comando en el save queda. Le dire al gm que lo puede probar asi como esta pero ya depues quiero cambiar el sistema de apuestas.
